### ISSUE TITLE
Fails to play local files.

### ISSUE THREAD

**Issue by robertapengelly** [stephengold/j-ogg-all#1]
If I use a URL to play a file then it works as expected but when I download the file and try playing it locally I get a header error.

![Screenshot from 2022-09-24 04-26-04](https://user-images.githubusercontent.com/55969885/192078099-de5de79f-1038-46d9-b687-2e6ba9d9c4f8.png)

It finds the first header but not any other headers after that as its all zeros (I think the getNextOggPacket() maybe returning null).

**Comment by robertapengelly** [comment]
Never mind solved it by adding this.sourceStream = sourceStream int the BasicStream constructor.

**Comment by stephengold** [comment]
Fixed in version 1.0.2.

Thank you @robertapengelly for the tip!
