### ISSUE TITLE
Extract album art.

### ISSUE THREAD

**Issue by robertapengelly** [stephengold/j-ogg-all#2]
Not exactly an issue but how do you extract the album art?  I know that it's within the comment header identified by METADATA_BLOCK_PICTURE and that it's base64 encoded, I just don't know how to extract the image after decoding it as it starts with 8 bytes before the mimetype and I don't know how to get to the actual image data.

I tried googling it but I can't find anything (at least nothing that helps) and I've looked at other projects but they don't seem to have an implementation to extract the image.

**Comment by stephengold** [comment]
Thanks for getting in touch.
Off-hand, I don't know what's needed.
I'm busy with other projects and won't investigate right now. However, I'll keep this open for future investigation.
If you find a solution, please let me know or submit a pull request.
