### ISSUE TITLE
[Question] Mixing multiple ogg/vorbis files into one ogg/vorbis stream/file 

### ISSUE THREAD

**Issue by zeppelinux** [stephengold/j-ogg-all#4]
Hi,

I want to implement software mixer that mixes multiple ogg/vorbis files (volume of each source should be adjustable) into the single ogg/vorbis stream/file. Is your library a proper tool for the project? If yes, what would be some high level steps for achieving this?

Thanks!

**Comment by stephengold** [comment]
Disclaimer: I'm not the original author of the library, just a maintainer.

As far as I know, the library can read OGG streams but not write them.  Therefore, I don't think it's suitable for the project you described.
